//This file was generated by GenerateAddHandlerDeclarations.py
//Do not edit it.
void AddBOOL(INktHookCallInfoPlugin &hcip);
void AddVOID(INktHookCallInfoPlugin &hcip);
void AddINT(INktHookCallInfoPlugin &hcip);
void AddUINT(INktHookCallInfoPlugin &hcip);
void AddHEX(INktHookCallInfoPlugin &hcip);
void AddHRESULT(INktHookCallInfoPlugin &hcip);
void AddNTSTATUS(INktHookCallInfoPlugin &hcip);
