// This section is automatically generated!

HRESULT OnICorProfilerCallback_QueryInterface(ICorProfilerCallback3 *_this, REFIID riid, LPVOID * ppvObject);
HRESULT OnICorProfilerCallback_Initialize(ICorProfilerCallback3 *_this, IUnknown * pICorProfilerInfoUnk);
HRESULT OnICorProfilerCallback_Shutdown(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_AppDomainCreationStarted(ICorProfilerCallback3 *_this, AppDomainID appDomainId);
HRESULT OnICorProfilerCallback_AppDomainCreationFinished(ICorProfilerCallback3 *_this, AppDomainID appDomainId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_AppDomainShutdownStarted(ICorProfilerCallback3 *_this, AppDomainID appDomainId);
HRESULT OnICorProfilerCallback_AppDomainShutdownFinished(ICorProfilerCallback3 *_this, AppDomainID appDomainId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_AssemblyLoadStarted(ICorProfilerCallback3 *_this, AssemblyID assemblyId);
HRESULT OnICorProfilerCallback_AssemblyLoadFinished(ICorProfilerCallback3 *_this, AssemblyID assemblyId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_AssemblyUnloadStarted(ICorProfilerCallback3 *_this, AssemblyID assemblyId);
HRESULT OnICorProfilerCallback_AssemblyUnloadFinished(ICorProfilerCallback3 *_this, AssemblyID assemblyId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_ModuleLoadStarted(ICorProfilerCallback3 *_this, ModuleID moduleId);
HRESULT OnICorProfilerCallback_ModuleLoadFinished(ICorProfilerCallback3 *_this, ModuleID moduleId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_ModuleUnloadStarted(ICorProfilerCallback3 *_this, ModuleID moduleId);
HRESULT OnICorProfilerCallback_ModuleUnloadFinished(ICorProfilerCallback3 *_this, ModuleID moduleId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_ModuleAttachedToAssembly(ICorProfilerCallback3 *_this, ModuleID moduleId, AssemblyID AssemblyId);
HRESULT OnICorProfilerCallback_ClassLoadStarted(ICorProfilerCallback3 *_this, ClassID classId);
HRESULT OnICorProfilerCallback_ClassLoadFinished(ICorProfilerCallback3 *_this, ClassID classId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_ClassUnloadStarted(ICorProfilerCallback3 *_this, ClassID classId);
HRESULT OnICorProfilerCallback_ClassUnloadFinished(ICorProfilerCallback3 *_this, ClassID classId, HRESULT hrStatus);
HRESULT OnICorProfilerCallback_FunctionUnloadStarted(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_JITCompilationStarted(ICorProfilerCallback3 *_this, FunctionID functionId, BOOL fIsSafeToBlock);
HRESULT OnICorProfilerCallback_JITCompilationFinished(ICorProfilerCallback3 *_this, FunctionID functionId, HRESULT hrStatus, BOOL fIsSafeToBlock);
HRESULT OnICorProfilerCallback_JITCachedFunctionSearchStarted(ICorProfilerCallback3 *_this, FunctionID functionId, BOOL * pbUseCachedFunction);
HRESULT OnICorProfilerCallback_JITCachedFunctionSearchFinished(ICorProfilerCallback3 *_this, FunctionID functionId, COR_PRF_JIT_CACHE result);
HRESULT OnICorProfilerCallback_JITFunctionPitched(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_JITInlining(ICorProfilerCallback3 *_this, FunctionID callerId, FunctionID calleeId, BOOL * pfShouldInline);
HRESULT OnICorProfilerCallback_ThreadCreated(ICorProfilerCallback3 *_this, ThreadID threadId);
HRESULT OnICorProfilerCallback_ThreadDestroyed(ICorProfilerCallback3 *_this, ThreadID threadId);
HRESULT OnICorProfilerCallback_ThreadAssignedToOSThread(ICorProfilerCallback3 *_this, ThreadID managedThreadId, DWORD osThreadId);
HRESULT OnICorProfilerCallback_RemotingClientInvocationStarted(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RemotingClientSendingMessage(ICorProfilerCallback3 *_this, LPGUID pCookie, BOOL fIsAsync);
HRESULT OnICorProfilerCallback_RemotingClientReceivingReply(ICorProfilerCallback3 *_this, LPGUID pCookie, BOOL fIsAsync);
HRESULT OnICorProfilerCallback_RemotingClientInvocationFinished(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RemotingServerReceivingMessage(ICorProfilerCallback3 *_this, LPGUID pCookie, BOOL fIsAsync);
HRESULT OnICorProfilerCallback_RemotingServerInvocationStarted(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RemotingServerInvocationReturned(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RemotingServerSendingReply(ICorProfilerCallback3 *_this, LPGUID pCookie, BOOL fIsAsync);
HRESULT OnICorProfilerCallback_UnmanagedToManagedTransition(ICorProfilerCallback3 *_this, FunctionID functionId, COR_PRF_TRANSITION_REASON reason);
HRESULT OnICorProfilerCallback_ManagedToUnmanagedTransition(ICorProfilerCallback3 *_this, FunctionID functionId, COR_PRF_TRANSITION_REASON reason);
HRESULT OnICorProfilerCallback_RuntimeSuspendStarted(ICorProfilerCallback3 *_this, COR_PRF_SUSPEND_REASON suspendReason);
HRESULT OnICorProfilerCallback_RuntimeSuspendFinished(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RuntimeSuspendAborted(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RuntimeResumeStarted(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RuntimeResumeFinished(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_RuntimeThreadSuspended(ICorProfilerCallback3 *_this, ThreadID threadId);
HRESULT OnICorProfilerCallback_RuntimeThreadResumed(ICorProfilerCallback3 *_this, ThreadID threadId);
HRESULT OnICorProfilerCallback_MovedReferences(ICorProfilerCallback3 *_this, ULONG cMovedObjectIDRanges, ObjectID * oldObjectIDRangeStart, ObjectID * newObjectIDRangeStart, ULONG * cObjectIDRangeLength);
HRESULT OnICorProfilerCallback_ObjectAllocated(ICorProfilerCallback3 *_this, ObjectID objectId, ClassID classId);
HRESULT OnICorProfilerCallback_ObjectsAllocatedByClass(ICorProfilerCallback3 *_this, ULONG cClassCount, ClassID * classIds, ULONG * cObjects);
HRESULT OnICorProfilerCallback_ObjectReferences(ICorProfilerCallback3 *_this, ObjectID objectId, ClassID classId, ULONG cObjectRefs, ObjectID * objectRefIds);
HRESULT OnICorProfilerCallback_RootReferences(ICorProfilerCallback3 *_this, ULONG cRootRefs, ObjectID * rootRefIds);
HRESULT OnICorProfilerCallback_ExceptionThrown(ICorProfilerCallback3 *_this, ObjectID thrownObjectId);
HRESULT OnICorProfilerCallback_ExceptionSearchFunctionEnter(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_ExceptionSearchFunctionLeave(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ExceptionSearchFilterEnter(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_ExceptionSearchFilterLeave(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ExceptionSearchCatcherFound(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_ExceptionOSHandlerEnter(ICorProfilerCallback3 *_this, UINT_PTR __unused);
HRESULT OnICorProfilerCallback_ExceptionOSHandlerLeave(ICorProfilerCallback3 *_this, UINT_PTR __unused);
HRESULT OnICorProfilerCallback_ExceptionUnwindFunctionEnter(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_ExceptionUnwindFunctionLeave(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ExceptionUnwindFinallyEnter(ICorProfilerCallback3 *_this, FunctionID functionId);
HRESULT OnICorProfilerCallback_ExceptionUnwindFinallyLeave(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ExceptionCatcherEnter(ICorProfilerCallback3 *_this, FunctionID functionId, ObjectID objectId);
HRESULT OnICorProfilerCallback_ExceptionCatcherLeave(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_COMClassicVTableCreated(ICorProfilerCallback3 *_this, ClassID wrappedClassId, REFGUID implementedIID, void * pVTable, ULONG cSlots);
HRESULT OnICorProfilerCallback_COMClassicVTableDestroyed(ICorProfilerCallback3 *_this, ClassID wrappedClassId, REFGUID implementedIID, void * pVTable);
HRESULT OnICorProfilerCallback_ExceptionCLRCatcherFound(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ExceptionCLRCatcherExecute(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ThreadNameChanged(ICorProfilerCallback3 *_this, ThreadID threadId, ULONG cchName, PWCHAR name);
HRESULT OnICorProfilerCallback_GarbageCollectionStarted(ICorProfilerCallback3 *_this, int cGenerations, BOOL * generationCollected, COR_PRF_GC_REASON reason);
HRESULT OnICorProfilerCallback_SurvivingReferences(ICorProfilerCallback3 *_this, ULONG cSurvivingObjectIDRanges, ObjectID * objectIDRangeStart, ULONG * cObjectIDRangeLength);
HRESULT OnICorProfilerCallback_GarbageCollectionFinished(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_FinalizeableObjectQueued(ICorProfilerCallback3 *_this, DWORD finalizerFlags, ObjectID objectID);
HRESULT OnICorProfilerCallback_RootReferences2(ICorProfilerCallback3 *_this, ULONG cRootRefs, ObjectID * rootRefIds, COR_PRF_GC_ROOT_KIND * rootKinds, COR_PRF_GC_ROOT_FLAGS * rootFlags, UINT_PTR * rootIds);
HRESULT OnICorProfilerCallback_HandleCreated(ICorProfilerCallback3 *_this, GCHandleID handleId, ObjectID initialObjectId);
HRESULT OnICorProfilerCallback_HandleDestroyed(ICorProfilerCallback3 *_this, GCHandleID handleId);
HRESULT OnICorProfilerCallback_InitializeForAttach(ICorProfilerCallback3 *_this, IUnknown * pCorProfilerInfoUnk, void * pvClientData, UINT cbClientData);
HRESULT OnICorProfilerCallback_ProfilerAttachComplete(ICorProfilerCallback3 *_this);
HRESULT OnICorProfilerCallback_ProfilerDetachSucceeded(ICorProfilerCallback3 *_this);

// End of automatically generated section.
