#pragma once

// This section is automatically generated!

enum class FunctionId
{
  QueryInterface = 0,
  Initialize = 1,
  Shutdown = 2,
  AppDomainCreationStarted = 3,
  AppDomainCreationFinished = 4,
  AppDomainShutdownStarted = 5,
  AppDomainShutdownFinished = 6,
  AssemblyLoadStarted = 7,
  AssemblyLoadFinished = 8,
  AssemblyUnloadStarted = 9,
  AssemblyUnloadFinished = 10,
  ModuleLoadStarted = 11,
  ModuleLoadFinished = 12,
  ModuleUnloadStarted = 13,
  ModuleUnloadFinished = 14,
  ModuleAttachedToAssembly = 15,
  ClassLoadStarted = 16,
  ClassLoadFinished = 17,
  ClassUnloadStarted = 18,
  ClassUnloadFinished = 19,
  FunctionUnloadStarted = 20,
  JITCompilationStarted = 21,
  JITCompilationFinished = 22,
  JITCachedFunctionSearchStarted = 23,
  JITCachedFunctionSearchFinished = 24,
  JITFunctionPitched = 25,
  JITInlining = 26,
  ThreadCreated = 27,
  ThreadDestroyed = 28,
  ThreadAssignedToOSThread = 29,
  RemotingClientInvocationStarted = 30,
  RemotingClientSendingMessage = 31,
  RemotingClientReceivingReply = 32,
  RemotingClientInvocationFinished = 33,
  RemotingServerReceivingMessage = 34,
  RemotingServerInvocationStarted = 35,
  RemotingServerInvocationReturned = 36,
  RemotingServerSendingReply = 37,
  UnmanagedToManagedTransition = 38,
  ManagedToUnmanagedTransition = 39,
  RuntimeSuspendStarted = 40,
  RuntimeSuspendFinished = 41,
  RuntimeSuspendAborted = 42,
  RuntimeResumeStarted = 43,
  RuntimeResumeFinished = 44,
  RuntimeThreadSuspended = 45,
  RuntimeThreadResumed = 46,
  MovedReferences = 47,
  ObjectAllocated = 48,
  ObjectsAllocatedByClass = 49,
  ObjectReferences = 50,
  RootReferences = 51,
  ExceptionThrown = 52,
  ExceptionSearchFunctionEnter = 53,
  ExceptionSearchFunctionLeave = 54,
  ExceptionSearchFilterEnter = 55,
  ExceptionSearchFilterLeave = 56,
  ExceptionSearchCatcherFound = 57,
  ExceptionOSHandlerEnter = 58,
  ExceptionOSHandlerLeave = 59,
  ExceptionUnwindFunctionEnter = 60,
  ExceptionUnwindFunctionLeave = 61,
  ExceptionUnwindFinallyEnter = 62,
  ExceptionUnwindFinallyLeave = 63,
  ExceptionCatcherEnter = 64,
  ExceptionCatcherLeave = 65,
  COMClassicVTableCreated = 66,
  COMClassicVTableDestroyed = 67,
  ExceptionCLRCatcherFound = 68,
  ExceptionCLRCatcherExecute = 69,
  ThreadNameChanged = 70,
  GarbageCollectionStarted = 71,
  SurvivingReferences = 72,
  GarbageCollectionFinished = 73,
  FinalizeableObjectQueued = 74,
  RootReferences2 = 75,
  HandleCreated = 76,
  HandleDestroyed = 77,
  InitializeForAttach = 78,
  ProfilerAttachComplete = 79,
  ProfilerDetachSucceeded = 80,
  _Count = 81,
};

enum class LinkerId
{
  AppDomainCreation = 0,
  AppDomainShutdown = 1,
  AssemblyLoad = 2,
  AssemblyUnload = 3,
  ModuleLoad = 4,
  ModuleUnload = 5,
  ClassLoad = 6,
  ClassUnload = 7,
  JITCompilation = 8,
  JITCachedFunctionSearch = 9,
  RemotingClientInvocation = 10,
  RuntimeSuspend = 11,
  RuntimeResume = 12,
  GarbageCollection = 13,
  _Count = 14,
};

// End of automatically generated section.
