enum CustomMessageCodes
{
  CUSTOM_MESSAGE_SEND_BUFFER = 1,
  CUSTOM_MESSAGE_SEND_MUTEX,              // unused
  CUSTOM_MESSAGE_SEND_FIRST_BUFFER,
  CUSTOM_MESSAGE_GET_SERVER_HANDLE,
  CUSTOM_MESSAGE_ALLOW_COMMAND_LINE_HASH,
  CUSTOM_MESSAGE_OPEN_SERVICE_WAS_CALLED,
  CUSTOM_MESSAGE_REQUEST_SETTINGS,
  CUSTOM_MESSAGE_THINAPP_CREATE_PROCESS,
  CUSTOM_MESSAGE_REQUEST_EXEC_MEMORY,
  CUSTOM_MESSAGE_REQUEST_INTERNET_STATUS_CALLBACK_HOOK,
  CUSTOM_MESSAGE_REQUEST_INTERNET_STATUS_CALLBACK_WIDE_HOOK,
  CUSTOM_MESSAGE_REQUEST_INTERNET_STATUS_CALLBACK_UNHOOK,
  CUSTOM_MESSAGE_REQUEST_INTERNET_STATUS_CALLBACK_WIDE_UNHOOK,
};
