//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int MaxStackTraceDepth {
            get {
                return ((int)(this["MaxStackTraceDepth"]));
            }
            set {
                this["MaxStackTraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3500")]
        public int FileSystemUpdateInterval {
            get {
                return ((int)(this["FileSystemUpdateInterval"]));
            }
            set {
                this["FileSystemUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2200")]
        public int RegistryUpdateInterval {
            get {
                return ((int)(this["RegistryUpdateInterval"]));
            }
            set {
                this["RegistryUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int TraceUpdateInterval {
            get {
                return ((int)(this["TraceUpdateInterval"]));
            }
            set {
                this["TraceUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTooltip {
            get {
                return ((bool)(this["ShowTooltip"]));
            }
            set {
                this["ShowTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MaxTooltipModules {
            get {
                return ((int)(this["MaxTooltipModules"]));
            }
            set {
                this["MaxTooltipModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int ComUpdateInterval {
            get {
                return ((int)(this["ComUpdateInterval"]));
            }
            set {
                this["ComUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpyStudio")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
            set {
                this["AppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5500")]
        public int DataInfoUpdateInterval {
            get {
                return ((int)(this["DataInfoUpdateInterval"]));
            }
            set {
                this["DataInfoUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint RegistryBinarySize {
            get {
                return ((uint)(this["RegistryBinarySize"]));
            }
            set {
                this["RegistryBinarySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ProcessName</string>
  <string>Pid</string>
  <string>Tid</string>
  <string>Caller</string>
  <string>Function</string>
  <string>ParamMain</string>
  <string>ParamDetails</string>
  <string>Result</string>
</ArrayOfString>")]
        public string FilterFieldsMain {
            get {
                return ((string)(this["FilterFieldsMain"]));
            }
            set {
                this["FilterFieldsMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ProcessName</string>
  <string>Caller</string>
  <string>StackFrame</string>
  <string>Function</string>
  <string>ParamMain</string>
  <string>ParamDetails</string>
  <string>Result</string>
</ArrayOfString>")]
        public string FilterFieldsCompare {
            get {
                return ((string)(this["FilterFieldsCompare"]));
            }
            set {
                this["FilterFieldsCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterMain {
            get {
                return ((string)(this["FilterMain"]));
            }
            set {
                this["FilterMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterCompare {
            get {
                return ((string)(this["FilterCompare"]));
            }
            set {
                this["FilterCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUINTAsHex {
            get {
                return ((bool)(this["ShowUINTAsHex"]));
            }
            set {
                this["ShowUINTAsHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activex,process,registry,windows creation,files,resources,common dialogs,exceptio" +
            "ns")]
        public string ActiveHookGroups {
            get {
                return ((string)(this["ActiveHookGroups"]));
            }
            set {
                this["ActiveHookGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportRegistryOnlyFromSelectedModules {
            get {
                return ((bool)(this["ExportRegistryOnlyFromSelectedModules"]));
            }
            set {
                this["ExportRegistryOnlyFromSelectedModules"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\DataModel.sdf")]
        public string DataModelConnectionString {
            get {
                return ((string)(this["DataModelConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<filters>\r\n    <filter type=\"contains\" include=\"False\">\r\n        <type>contains</" +
            "type>\r\n        <include>false</include>\r\n        <enabled>true</enabled>\r\n      " +
            "  <field>ParamMain</field>\r\n        <value>uxtheme.dll</value>\r\n    </filter>\r\n<" +
            "/filters>")]
        public string FilterMainDefault {
            get {
                return ((string)(this["FilterMainDefault"]));
            }
            set {
                this["FilterMainDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<filters>
    <filter type=""contains"" include=""False"">
        <type>contains</type>
        <include>false</include>
        <enabled>true</enabled>
        <field>ParamMain</field>
        <value>uxtheme.dll</value>
    </filter>
    <filter type=""is"" include=""False"">
        <type>Is</type>
        <include>false</include>
        <enabled>false</enabled>
        <field>Caller</field>
        <value>nt0_dll.dll</value>
    </filter>
</filters>")]
        public string FilterCompareDefault {
            get {
                return ((string)(this["FilterCompareDefault"]));
            }
            set {
                this["FilterCompareDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MinStackTraceDepth {
            get {
                return ((int)(this["MinStackTraceDepth"]));
            }
            set {
                this["MinStackTraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReportInternetReadFileBuffers {
            get {
                return ((bool)(this["ReportInternetReadFileBuffers"]));
            }
            set {
                this["ReportInternetReadFileBuffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterKey {
            get {
                return ((string)(this["FilterKey"]));
            }
            set {
                this["FilterKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExecutePath {
            get {
                return ((string)(this["LastExecutePath"]));
            }
            set {
                this["LastExecutePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DlgPeep {
            get {
                return ((bool)(this["DlgPeep"]));
            }
            set {
                this["DlgPeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExecuteParameters {
            get {
                return ((string)(this["LastExecuteParameters"]));
            }
            set {
                this["LastExecuteParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcMonLoadKernelCalls {
            get {
                return ((bool)(this["ProcMonLoadKernelCalls"]));
            }
            set {
                this["ProcMonLoadKernelCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcMonShowKernelStack {
            get {
                return ((bool)(this["ProcMonShowKernelStack"]));
            }
            set {
                this["ProcMonShowKernelStack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemMergeLayerPaths {
            get {
                return ((bool)(this["FileSystemMergeLayerPaths"]));
            }
            set {
                this["FileSystemMergeLayerPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<filters>
    <filter type=""contains"" include=""False"">
        <type>contains</type>
        <include>false</include>
        <enabled>true</enabled>
        <field>ParamMain</field>
        <value>uxtheme.dll</value>
    </filter>
    <filter type=""is"" include=""False"">
        <type>is</type>
        <include>false</include>
        <enabled>false</enabled>
        <field>Caller</field>
        <value>nt0_dll.dll</value>
    </filter>
</filters>")]
        public string FilterCompareLoadDefault {
            get {
                return ((string)(this["FilterCompareLoadDefault"]));
            }
            set {
                this["FilterCompareLoadDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<filters>\r\n    <filter type=\"contains\" include=\"False\">\r\n        <type>contains</" +
            "type>\r\n        <include>false</include>\r\n        <enabled>true</enabled>\r\n      " +
            "  <field>ParamMain</field>\r\n        <value>uxtheme.dll</value>\r\n    </filter>\r\n<" +
            "/filters>")]
        public string FilterMainLoadDefault {
            get {
                return ((string)(this["FilterMainLoadDefault"]));
            }
            set {
                this["FilterMainLoadDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterMainLoad {
            get {
                return ((string)(this["FilterMainLoad"]));
            }
            set {
                this["FilterMainLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterCompareLoad {
            get {
                return ((string)(this["FilterCompareLoad"]));
            }
            set {
                this["FilterCompareLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemShowTree {
            get {
                return ((bool)(this["FileSystemShowTree"]));
            }
            set {
                this["FileSystemShowTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemHideQueryAttributes {
            get {
                return ((bool)(this["FileSystemHideQueryAttributes"]));
            }
            set {
                this["FileSystemHideQueryAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemMergeLayerPathsCompare {
            get {
                return ((bool)(this["FileSystemMergeLayerPathsCompare"]));
            }
            set {
                this["FileSystemMergeLayerPathsCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsUserName {
            get {
                return ((string)(this["RunAsUserName"]));
            }
            set {
                this["RunAsUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunAsPassword {
            get {
                return ((string)(this["RunAsPassword"]));
            }
            set {
                this["RunAsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemMergeWowPaths {
            get {
                return ((bool)(this["FileSystemMergeWowPaths"]));
            }
            set {
                this["FileSystemMergeWowPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemMergeWowPathsCompare {
            get {
                return ((bool)(this["FileSystemMergeWowPathsCompare"]));
            }
            set {
                this["FileSystemMergeWowPathsCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemShowStartupModules {
            get {
                return ((bool)(this["FileSystemShowStartupModules"]));
            }
            set {
                this["FileSystemShowStartupModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemShowStartupModulesCompare {
            get {
                return ((bool)(this["FileSystemShowStartupModulesCompare"]));
            }
            set {
                this["FileSystemShowStartupModulesCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemHideQueryAttributesCompare {
            get {
                return ((bool)(this["FileSystemHideQueryAttributesCompare"]));
            }
            set {
                this["FileSystemHideQueryAttributesCompare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathLastSelectedAppFolder {
            get {
                return ((string)(this["PathLastSelectedAppFolder"]));
            }
            set {
                this["PathLastSelectedAppFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathLastSelectedLogFolder {
            get {
                return ((string)(this["PathLastSelectedLogFolder"]));
            }
            set {
                this["PathLastSelectedLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathLastSelectedTemplateFolder {
            get {
                return ((string)(this["PathLastSelectedTemplateFolder"]));
            }
            set {
                this["PathLastSelectedTemplateFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsyncReg {
            get {
                return ((bool)(this["AsyncReg"]));
            }
            set {
                this["AsyncReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegistryMergeWowPaths {
            get {
                return ((bool)(this["RegistryMergeWowPaths"]));
            }
            set {
                this["RegistryMergeWowPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegistryMergeClassPaths {
            get {
                return ((bool)(this["RegistryMergeClassPaths"]));
            }
            set {
                this["RegistryMergeClassPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UIUpdateInterval {
            get {
                return ((int)(this["UIUpdateInterval"]));
            }
            set {
                this["UIUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spy")]
        public string LastDefaultLoadExtension {
            get {
                return ((string)(this["LastDefaultLoadExtension"]));
            }
            set {
                this["LastDefaultLoadExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FullStackInfo {
            get {
                return ((bool)(this["FullStackInfo"]));
            }
            set {
                this["FullStackInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonitorDotNetGc {
            get {
                return ((bool)(this["MonitorDotNetGc"]));
            }
            set {
                this["MonitorDotNetGc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonitorDotNetJit {
            get {
                return ((bool)(this["MonitorDotNetJit"]));
            }
            set {
                this["MonitorDotNetJit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonitorDotNetExceptions {
            get {
                return ((bool)(this["MonitorDotNetExceptions"]));
            }
            set {
                this["MonitorDotNetExceptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MonitorDotNetObjectAllocations {
            get {
                return ((bool)(this["MonitorDotNetObjectAllocations"]));
            }
            set {
                this["MonitorDotNetObjectAllocations"] = value;
            }
        }
    }
}
